from os.path import join 

SECRET_FOLDER = "/secrets"

MASTODON_ACCESS_TOKEN_PATH = join(SECRET_FOLDER, "MASTODON_ACCESS_TOKEN")
MASTODON_ACCESS_TOKEN = open(MASTODON_ACCESS_TOKEN_PATH).read().strip()